#!/usr/bin/env python3
"""Render `velox --help` into the generated block of `docs/reference/cli.md`.

    uv run python scripts/gen_cli_reference.py            # write
    uv run python scripts/gen_cli_reference.py --check    # fail if stale

Every other reference page is rendered from docstrings by mkdocstrings; argparse has none to
render, so the flags reach the site through this script instead. Prose outside the markers in
`docs/reference/cli.md` is hand-written and left alone.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from functools import partial
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "docs" / "reference" / "cli.md"

BEGIN = "<!-- generated by scripts/gen_cli_reference.py -- do not edit below this line -->"
END = "<!-- end generated -->"

# Fixed, so the usage block is the same whatever terminal the script is run from.
USAGE_WIDTH = 94

# The rest of `docs/` is hard-wrapped at 100 columns; generated prose matches it.
WRAP_WIDTH = 100

# Characters Markdown would read as syntax. Help strings are plain prose written for a terminal --
# `[tool.velox]`, `*args`, `tmp_path_factory` -- so every one of them reaches the page literally.
ESCAPE = "\\`*_[]<>#"


def _escape(text: str) -> str:
    for char in ESCAPE:
        text = text.replace(char, "\\" + char)
    return text


def _declared_metavar(action: argparse.Action) -> str:
    """The `metavar=` the action was declared with, or the empty string if it has none.

    A metavar is a tuple when one flag takes several values, one name per value.
    """
    if action.metavar is None:
        return ""
    if isinstance(action.metavar, str):
        return action.metavar
    return " ".join(action.metavar)


def _metavar(action: argparse.Action) -> str:
    """What follows the flag in `-k EXPR`, or the empty string for a flag taking no value."""
    if action.nargs == 0:
        return ""
    if declared := _declared_metavar(action):
        return declared
    if action.choices:
        return "{" + ",".join(str(choice) for choice in action.choices) + "}"
    return action.dest.upper()


def _invocation(action: argparse.Action) -> str:
    if not action.option_strings:
        return _declared_metavar(action) or action.dest
    metavar = _metavar(action)
    return ", ".join(f"{opt} {metavar}".rstrip() for opt in action.option_strings)


def _help(action: argparse.Action) -> str:
    """The action's help text with argparse's own `%(...)s` placeholders filled in."""
    text = " ".join((action.help or "").split())
    params = {key: value for key, value in vars(action).items() if value is not argparse.SUPPRESS}
    params["prog"] = "velox"
    return text % params


def render(parser: argparse.ArgumentParser) -> str:
    parser.formatter_class = partial(argparse.HelpFormatter, width=USAGE_WIDTH)
    lines = [BEGIN, "", "```console", "$ velox --help", parser.format_usage().rstrip(), "```"]
    # argparse exposes its groups only privately. `_group_actions` is the group's own actions;
    # `_actions` on a group is the parser-wide list, which would file every flag under the first
    # heading.
    for group in parser._action_groups:
        actions = [a for a in group._group_actions if a.help is not argparse.SUPPRESS]
        if not actions:
            continue
        lines += ["", f"## {group.title.capitalize()}" if group.title else "## Arguments"]
        for action in actions:
            body = textwrap.fill(_escape(_help(action)), width=WRAP_WIDTH)
            lines += ["", f"### `{_invocation(action)}`", "", body]
    lines += ["", END]
    return "\n".join(lines) + "\n"


def _splice(page: str, block: str) -> str:
    start, end = page.find(BEGIN), page.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{PAGE} is missing the generated-block markers")
    return page[:start] + block + page[end + len(END) :].lstrip("\n")


def main(argv: list[str] | None = None) -> int:
    args = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    args.add_argument("--check", action="store_true", help="Exit 1 if the page is out of date.")
    check = args.parse_args(argv).check

    from velox.cli import build_parser

    current = PAGE.read_text()
    updated = _splice(current, render(build_parser()))
    if check:
        if current != updated:
            print(f"{PAGE.relative_to(REPO)} is out of date: run just docs cli", file=sys.stderr)
            return 1
        return 0
    if current != updated:
        PAGE.write_text(updated)
        print(f"wrote {PAGE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
