#!/usr/bin/env python3
"""Render `voci_migrate.matrix` into the generated block of `docs/migrate/matrix.md`.

    uv run python scripts/gen_support_matrix.py            # write
    uv run python scripts/gen_support_matrix.py --check    # fail if stale

The matrix is the one place a construct's classification is decided, so the parity page is
rendered from it rather than restated beside it. Prose outside the markers in
`docs/migrate/matrix.md` is hand-written and left alone.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from voci_migrate import matrix
from voci_migrate.matrix import Construct

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "docs" / "migrate" / "matrix.md"

BEGIN = "<!-- generated by scripts/gen_support_matrix.py -- do not edit below this line -->"
END = "<!-- end generated -->"

# A handful of matrix targets name an outcome rather than a voci spelling, so code font would
# read as an API they could be typed as.
PROSE_TARGETS = frozenset({"deleted", "dropped"})


def _code(text: str) -> str:
    """A matrix subject or target in code font, where it is code rather than a phrase.

    A comma-separated list of bare names is marked up name by name; a single call spelling keeps
    the commas inside its parentheses and is marked up whole.
    """
    if text in PROSE_TARGETS:
        return text
    parts = text.split(", ")
    if all(" " not in part and part.count("(") == part.count(")") for part in parts):
        return ", ".join(f"`{part}`" for part in parts)
    head, _, tail = text.partition("(")
    if tail.endswith(")") and " " not in head:
        return f"`{text}`"
    return text


def _cell(text: str) -> str:
    """One table cell: single-line, with the column separator escaped out of the text."""
    return " ".join(text.split()).replace("|", "\\|")


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    return [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows),
    ]


def _target(construct: Construct) -> str:
    return _code(construct.target) if construct.target else "—"


def _solo(construct: Construct) -> str:
    """The sentence appended to a row whose tests lose their overlap with the rest of the suite."""
    return " Tests using it run alone." if construct.serialized else ""


def render() -> str:
    detected = [c for c in matrix.CONSTRUCTS if c.detected]
    by_disposition = {
        disposition: [c for c in detected if c.disposition == disposition]
        for disposition in matrix.Disposition
    }

    lines = [BEGIN, ""]

    lines += ["## Converts as it stands", ""]
    lines += [
        "Nobody has to read the diff for these. The conversion rewrites them and the audit counts "
        "the tests carrying them as clean.",
        "",
    ]
    lines += _table(
        ["Code", "pytest", "voci", "Notes"],
        [
            [c.code, _code(c.subject), _target(c), c.note + _solo(c)]
            for c in by_disposition[matrix.Disposition.MECHANICAL]
        ],
    )

    lines += ["", "## Converts, with something to check", ""]
    lines += [
        "These convert to working code, but something shifted on the way. The rewrite leaves a "
        "`VOCI-TODO[code]` comment in the source at each one.",
        "",
    ]
    lines += _table(
        ["Code", "pytest", "voci", "What shifted", "What to check"],
        [
            [c.code, _code(c.subject), _target(c), c.note + _solo(c), c.action or "—"]
            for c in by_disposition[matrix.Disposition.MARKER]
        ],
    )

    lines += ["", "## Needs a decision first", ""]
    lines += [
        "voci has somewhere for these to go, but not one the conversion can pick on its own. "
        "Each is a blocked test until the suite is changed by hand.",
        "",
    ]
    lines += _table(
        ["Code", "pytest", "Why", "What to do"],
        [
            [c.code, _code(c.subject), c.note, c.action or "—"]
            for c in by_disposition[matrix.Disposition.REFUSED]
        ],
    )

    lines += ["", "## No voci equivalent", ""]
    lines += [
        "voci provides nothing that plays these parts, so a suite that leans on one has to do "
        "without it or keep that part under pytest.",
        "",
    ]
    lines += _table(
        ["Code", "pytest", "Why", "What to do instead"],
        [
            [c.code, _code(c.subject), c.note, c.action or "—"]
            for c in by_disposition[matrix.Disposition.UNSUPPORTED]
        ],
    )

    lines += ["", "## Survives conversion, changes under concurrency", ""]
    lines += [
        "These translate as written and then mean something different, because voci overlaps the "
        "tests that pytest ran one at a time. Most cost the tests carrying them their overlap "
        "with the rest of the suite.",
        "",
    ]
    lines += _table(
        ["Code", "Construct", "What changes", "What to do"],
        [
            [c.code, _code(c.subject), c.note + _solo(c), c.action or "—"]
            for c in by_disposition[matrix.Disposition.HAZARD]
        ],
    )

    blind = [c for c in matrix.CONSTRUCTS if not c.detected]
    lines += ["", "## What no scan can see", ""]
    lines += [
        "A dump records what pytest resolved and a parse records what the sources say. Neither "
        "reaches these, so the audit names them in its report rather than counting them.",
        "",
    ]
    lines += _table(
        ["Code", "Construct", "Why it is invisible", "What to do"],
        [[c.code, _code(c.subject), c.note, c.action or "—"] for c in blind],
    )

    lines += ["", "## Installed plugins", ""]
    lines += [
        "What migration makes of each plugin it recognizes, by the matrix row that classifies it: "
        "`VC320` is deleted outright, `VC321` translates into something voci already has, "
        "`VC322` survives but mutates state the whole process shares, and `VC323` has no voci "
        "path. A plugin absent from this table is reported as unrecognized rather than assumed "
        "harmless.",
        "",
    ]
    lines += _table(
        ["Plugin", "Code", "Disposition", "Notes"],
        [
            [
                f"`{recipe.dist}`",
                recipe.code,
                str(matrix.construct(recipe.code).disposition),
                recipe.note,
            ]
            for recipe in matrix.PLUGINS.values()
        ],
    )

    lines += ["", "## pytest's builtin fixtures", ""]
    lines += [
        "Every fixture pytest provides without the suite declaring it, and the row that decides "
        "what a request for it becomes.",
        "",
    ]
    lines += _table(
        ["Fixture", "Code", "Becomes"],
        [
            [f"`{name}`", code, _target(matrix.construct(code))]
            for name, code in matrix.BUILTIN_FIXTURES.items()
        ],
    )

    lines += ["", END]
    return "\n".join(lines) + "\n"


def _splice(page: str, block: str) -> str:
    start, end = page.find(BEGIN), page.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{PAGE} is missing the generated-block markers")
    return page[:start] + block + page[end + len(END) :].lstrip("\n")


def main(argv: list[str] | None = None) -> int:
    args = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    args.add_argument("--check", action="store_true", help="Exit 1 if the page is out of date.")
    check = args.parse_args(argv).check

    current = PAGE.read_text()
    updated = _splice(current, render())
    if check:
        if current != updated:
            print(f"{PAGE.relative_to(REPO)} is out of date: run just docs matrix", file=sys.stderr)
            return 1
        return 0
    if current != updated:
        PAGE.write_text(updated)
        print(f"wrote {PAGE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
